package absensi;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import java.sql.*;  // Untuk koneksi dan manipulasi database
import javax.swing.*;  // Untuk komponen GUI seperti JOptionPane dan JFrame
import javax.swing.table.*;  // Untuk DefaultTableModel yang digunakan di JTable
import java.text.SimpleDateFormat;  // Untuk format tanggal
import com.toedter.calendar.JDateChooser;  // Untuk komponen pemilih tanggal (JDateChooser)



// Untuk komponen pemilih tanggal (JDateChooser)

/**
 *
 * @author ASUS
 */
public class Absensi extends javax.swing.JFrame {
    private JDateChooser tgl; // Deklarasi variabel tgl
    

    public Absensi() {
        initComponents(); // Memuat komponen GUI
        tgl = new JDateChooser(); // Inisialisasi JDateChooser
        add(tgl); // Menambahkan ke GUI (jika belum ditambahkan)
        tampil_data();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idAbsensi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tb_simpan = new javax.swing.JButton();
        tb_edit = new javax.swing.JButton();
        tb_hapus = new javax.swing.JButton();
        tb_batal = new javax.swing.JButton();
        tb_cari = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        cari = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable = new javax.swing.JTable();
        status = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        kalender = new com.toedter.calendar.JDateChooser();
        jLabel9 = new javax.swing.JLabel();
        gender = new javax.swing.JComboBox<>();
        tanggal = new javax.swing.JLabel();
        noHp = new javax.swing.JTextField();
        idPegawai = new javax.swing.JComboBox<>();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setText("ABSENSI PEGAWAI");

        jLabel2.setText("Id Absensi");

        idAbsensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idAbsensiActionPerformed(evt);
            }
        });

        jLabel3.setText("Id Pegawai ");

        jLabel4.setText("Status");

        tb_simpan.setBackground(new java.awt.Color(165, 222, 255));
        tb_simpan.setText("Simpan");
        tb_simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_simpanActionPerformed(evt);
            }
        });

        tb_edit.setBackground(new java.awt.Color(165, 221, 255));
        tb_edit.setText("Edit");
        tb_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_editActionPerformed(evt);
            }
        });

        tb_hapus.setBackground(new java.awt.Color(165, 222, 255));
        tb_hapus.setText("Hapus");
        tb_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_hapusActionPerformed(evt);
            }
        });

        tb_batal.setBackground(new java.awt.Color(165, 222, 255));
        tb_batal.setText("Batal");
        tb_batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_batalActionPerformed(evt);
            }
        });

        tb_cari.setText("Cari");
        tb_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_cariActionPerformed(evt);
            }
        });

        jLabel6.setText("Cari");

        jTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable);

        status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hadir", "Cuti", "Sakit", "Alpa" }));
        status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusActionPerformed(evt);
            }
        });

        jLabel8.setText("No. Hp");

        kalender.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                kalenderPropertyChange(evt);
            }
        });

        jLabel9.setText("Gender");

        gender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan" }));

        tanggal.setText("Tanggal");

        noHp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noHpActionPerformed(evt);
            }
        });

        idPegawai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tb_cari)
                                .addGap(168, 168, 168))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 668, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(status, 0, 211, Short.MAX_VALUE)
                            .addComponent(idAbsensi, javax.swing.GroupLayout.DEFAULT_SIZE, 211, Short.MAX_VALUE)
                            .addComponent(idPegawai, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(tanggal, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(kalender, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
                            .addComponent(noHp)
                            .addComponent(gender, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tb_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(tb_simpan)
                                .addGap(78, 78, 78)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tb_hapus)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tb_batal)
                        .addGap(197, 197, 197))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(185, 185, 185))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(idAbsensi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(noHp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(idPegawai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tanggal))
                    .addComponent(kalender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_simpan)
                    .addComponent(tb_edit)
                    .addComponent(tb_hapus)
                    .addComponent(tb_batal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tb_cari)
                    .addComponent(cari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(157, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void idAbsensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idAbsensiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idAbsensiActionPerformed

    private void tb_simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_simpanActionPerformed
                                          
    try {
        // Mengambil nilai dari komponen yang benar
        String idabsensi = idAbsensi.getText();  
        String idpegawai = (String) idPegawai.getSelectedItem(); 
        String statusSelected = (String) status.getSelectedItem();  
        String jammasuk = jamMasuk.getText();  
        String jamkeluar = jamKeluar.getText();  
        java.sql.Date tanggal = new java.sql.Date(kalender.getDate().getTime());

        // Menyusun query SQL dengan prepared statement
        String sql = "INSERT INTO absen_pegawai (id_absen, id_pegawai, status, jam_masuk, jam_keluar, tanggal) VALUES (?, ?, ?, ?, ?, ? )";

        // Mendapatkan koneksi ke database
        java.sql.Connection conn = absensi.Koneksi.koneksiDB();
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);

        pst.setString(1, idabsensi);
        pst.setString(2, idpegawai);
        pst.setString(3, statusSelected);
        pst.setString(4, jammasuk);
        pst.setString(5, jamkeluar);
        pst.setString(6, tanggal.toString());
        
        pst.executeUpdate();
        JOptionPane.showMessageDialog(null, "Berhasil disimpan");
        tampil_data();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Gagal disimpan");
        System.out.println(e.getMessage());
    }
}
    }//GEN-LAST:event_tb_simpanActionPerformed

    private void tb_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_cariActionPerformed
       try {
    java.sql.Connection conn=(java.sql.Connection)absensi.Koneksi.koneksiDB();
    String sql = "Select * from absen_pegawai where id_pegawai='"+cari.getText()+"'";
    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
    ResultSet rs = pst.executeQuery(sql);
    if (rs.next()){
         idAbsensi.getText();  
         idPegawai.getSelectedItem(); 
         status.getSelectedItem();  
         jamMasuk.getText();  
         jamKeluar.getText();  
        kalender.setDate(null); 
        JOptionPane.showMessageDialog(null,"Data absen_pegawai : "
        + cari.getText() + " ditemukan, Apakah Anda Ingin Mengedit atau Menghapus?");
    }
} catch (Exception e){}
cari.requestFocus();
    }//GEN-LAST:event_tb_cariActionPerformed

    private void statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_statusActionPerformed

    private void kalenderPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_kalenderPropertyChange
         if (kalender.getDate() != null) {
        SimpleDateFormat format = new SimpleDateFormat("yyyy-MM-dd");
        String tgl_lahir = format.format(kalender.getDate());
        System.out.println("Tanggal: " + kalender); // Debug atau cetak hasil
        }
    }//GEN-LAST:event_kalenderPropertyChange

    private void tb_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_editActionPerformed
       try {
   
    // Mengatur nilai untuk parameter
    String idabsensi = idAbsensi.getText();  
    String idpegawai = (String) idPegawai.getSelectedItem();  
    String statusSelected = (String) status.getSelectedItem(); 
    String genderSelected = (String) gender.getSelectedItem();  
    String jammasuk = jamMasuk.getText();  
    String jamkeluar = jamKeluar.getText();  
    String hpText = noHp.getText(); 
    java.sql.Date tanggal = new java.sql.Date(kalender.getDate().getTime());  
   
 java.sql.Connection conn = (java.sql.Connection) absensi.Koneksi.koneksiDB();
String sql = "UPDATE absen_pegawai SET id_pegawai=?, status=?, jam_masuk=?, jam_keluar=?, tanggal=? WHERE id_absen=?";
    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
    
        pst.setString(1, idpegawai);
        pst.setString(2, statusSelected);
        pst.setString(3, jammasuk);
        pst.setString(4, jamkeluar);
        pst.setString(5, tanggal.toString());
        pst.setString(6, idabsensi);
        pst.executeUpdate();

    JOptionPane.showMessageDialog(null, "Data berhasil di Koreksi");
    tampil_data();
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Proses Edit data Gagal");
    System.out.println(e.getMessage());
}

    }//GEN-LAST:event_tb_editActionPerformed

    private void tb_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_hapusActionPerformed
  try {
   
    java.sql.Connection conn = absensi.Koneksi.koneksiDB();

    String idabsensi = idAbsensi.getText().trim();
    if (idabsensi.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Nomor tidak boleh kosong!");
        return;
    }
    
    String sql = "DELETE FROM absen_pegawai WHERE id_absen = ?";
    java.sql.PreparedStatement pst = conn.prepareStatement(sql);
    pst.setString(1, idabsensi);
    int rowsAffected = pst.executeUpdate();
    if (rowsAffected > 0) {
        JOptionPane.showMessageDialog(null, "Data berhasil dihapus");
    } else {
        JOptionPane.showMessageDialog(null, "Data tidak ditemukan");
    }
    // Panggil method untuk menampilkan data (jika ada)
    tampil_data();
    
    // Tutup PreparedStatement dan koneksi
    pst.close();
    conn.close();
    
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Proses penghapusan gagal");
    System.out.println("Error: " + e.getMessage());
    e.printStackTrace();  
}

    }//GEN-LAST:event_tb_hapusActionPerformed

    private void tb_batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_batalActionPerformed
         idAbsensi.setText("");
        idPegawai.setSelectedItem("");
        status.setSelectedItem("");  
        jamMasuk.setText("");  
        jamKeluar.setText("");  
        kalender.setDate(null);       
    }//GEN-LAST:event_tb_batalActionPerformed

    private void noHpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noHpActionPerformed
        try {

            String idPegawaiValue = (String) idPegawai.getSelectedItem();
            if (idPegawaiValue == null || idPegawaiValue.trim().isEmpty()) {
                JOptionPane.showMessageDialog(null, "ID Pegawai tidak boleh kosong.");
                return;
            }

            java.sql.Connection conn = absensi.Koneksi.koneksiDB();
            if (conn == null) {
                JOptionPane.showMessageDialog(null, "Gagal terhubung ke database.");
                return;
            }

            System.out.println("Koneksi berhasil. ID Pegawai: " + idPegawaiValue);

            String sql = "SELECT no_telepon FROM pegawai WHERE id_pegawai = ?";

            java.sql.PreparedStatement pst = conn.prepareStatement(sql);

            pst.setString(1, idPegawaiValue);

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {

                String noTelepon = rs.getString("no_telepon");

                noHp.setText(noTelepon);

                JOptionPane.showMessageDialog(null, "Nomor telepon berhasil ditemukan: " + noTelepon);
            } else {

                JOptionPane.showMessageDialog(null, "Data pegawai tidak ditemukan.");
            }

            rs.close();
            pst.close();
            conn.close();
        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Terjadi kesalahan: " + e.getMessage());
            e.printStackTrace();
        }
    }//GEN-LAST:event_noHpActionPerformed
public void tampil_data() {
    DefaultTableModel tabel = new DefaultTableModel();
    tabel.addColumn("Id Absensi");
    tabel.addColumn("Id Pegawai");
    tabel.addColumn("Tanggal");
    tabel.addColumn("Jam Masuk");
    tabel.addColumn("Jam Keluar");
    tabel.addColumn("Status");
    

    try {
        // Membuat koneksi ke database
        java.sql.Connection conn = (java.sql.Connection) absensi.Koneksi.koneksiDB();
        String sql = "SELECT * FROM absen_pegawai";
        java.sql.PreparedStatement pst = conn.prepareStatement(sql);
        java.sql.ResultSet rs = pst.executeQuery();

        // Mengisi tabel dengan data dari database
        while (rs.next()) {
            tabel.addRow(new Object[]{
                rs.getString("id_absen"), // Kolom 1
                rs.getString("id_pegawai"), // Kolom 2
                rs.getString("tanggal"), // Kolom 3
                rs.getString("jam_masuk"), // Kolom 4
                rs.getString("jam_keluar"), // Kolom 5
                rs.getString("status"), // Kolom 6
            });
        }

        // Menampilkan data ke dalam jTable
        jTable.setModel(tabel);

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }
}

    /**
     * @param args the command line arguments
     */
    public  void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Absensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Absensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Absensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Absensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Absensi().setVisible(true);
        });
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cari;
    private javax.swing.JComboBox<String> gender;
    private javax.swing.JTextField idAbsensi;
    private javax.swing.JComboBox<String> idPegawai;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable;
    private com.toedter.calendar.JDateChooser kalender;
    private javax.swing.JTextField noHp;
    private javax.swing.JComboBox<String> status;
    private javax.swing.JLabel tanggal;
    private javax.swing.JButton tb_batal;
    private javax.swing.JButton tb_cari;
    private javax.swing.JButton tb_edit;
    private javax.swing.JButton tb_hapus;
    private javax.swing.JButton tb_simpan;
    // End of variables declaration//GEN-END:variables

